# Generated by Django 4.2.10 on 2026-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_email_book_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_books_read',
            field=models.IntegerField(default=0),
        ),
    ]
