# Generated by Django 4.2.10 on 2026-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_on_homepage', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['-pub_date'],
            },
        ),
    ]
