# Generated by Django 4.2.10 on 2026-01-31 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_announcement_end_date_alter_announcement_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ALERT', 'Alert'), ('OVERDUE', 'Overdue Reminder'), ('NEW_BOOK', 'New Book Available')], default='INFO', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
