# Generated by Django 4.2.10 on 2026-02-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='ab_test_variant',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='clicked_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_emails', models.BooleanField(default=True)),
                ('transaction_emails', models.BooleanField(default=True)),
                ('reading_emails', models.BooleanField(default=True)),
                ('community_emails', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Summary'), ('MONTHLY', 'Monthly Newsletter')], default='IMMEDIATE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
