# Generated by Django 4.2.10 on 2026-02-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_emaillog_ab_test_variant_emaillog_campaign_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='ab_test_variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
