# Generated by Django 4.2.10 on 2026-05-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_emaillog_ab_test_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('WELCOME', 'Welcome Email'), ('OVERDUE', 'Overdue Alert'), ('BOOK_ISSUED', 'Book Issued'), ('BOOK_RETURNED', 'Book Returned'), ('NEW_BOOK_ALERT', 'New Book Alert'), ('READING_STREAK', 'Reading Streak'), ('BOOKS_READ_MILESTONE', 'Books Read Milestone'), ('GENERAL', 'General Notification')], max_length=40),
        ),
    ]
